export const FILE_DOWNLOAD_REQUEST = 'FILE_DOWNLOAD_REQUEST';
export const FILE_DOWNLOAD_SUCCESS = 'FILE_DOWNLOAD_SUCCESS';
export const FILE_DOWNLOAD_FAIL = 'FILE_DOWNLOAD_FAIL';
export const FILE_DOWNLOAD_RESET = 'FILE_DOWNLOAD_RESET';

export const FILE_VIEW_REQUEST = 'FILE_VIEW_REQUEST';
export const FILE_VIEW_SUCCESS = 'FILE_VIEW_SUCCESS';
export const FILE_VIEW_FAIL = 'FILE_VIEW_FAIL';
export const FILE_VIEW_RESET = 'FILE_VIEW_RESET';
