export const INVOICE_CREATE_REQUEST = 'INVOICE_CREATE_REQUEST';
export const INVOICE_CREATE_SUCCESS = 'INVOICE_CREATE_SUCCESS';
export const INVOICE_CREATE_ERROR = 'INVOICE_CREATE_ERROR';
export const INVOICE_CREATE_RESET = 'INVOICE_CREATE_RESET';

export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST';
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS';
export const INVOICE_LIST_ERROR = 'INVOICE_LIST_ERROR';
export const INVOICE_LIST_RESET = 'INVOICE_LIST_RESET';

export const INVOICE_DETAILS_REQUEST = 'INVOICE_DETAILS_REQUEST';
export const INVOICE_DETAILS_SUCCESS = 'INVOICE_DETAILS_SUCCESS';
export const INVOICE_DETAILS_ERROR = 'INVOICE_DETAILS_ERROR';
export const INVOICE_DETAILS_RESET = 'INVOICE_DETAILS_RESET';
