export const STOCK_HISTORY_REQUEST = 'STOCK_HISTORY_REQUEST';
export const STOCK_HISTORY_SUCCESS = 'STOCK_HISTORY_SUCCESS';
export const STOCK_HISTORY_ERROR = 'STOCK_HISTORY_ERROR';
export const STOCK_HISTORY_RESET = 'STOCK_HISTORY_RESET';
